### ISSUE TITLE
AttributeError: 'NeuroNER' object has no attribute 'sess'

### ISSUE THREAD

**Issue by Mahmedturk** [Franck-Dernoncourt/NeuroNER#143] opened 2019-04-07 00:34 UTC
Hi,

I get the the following error with conll dataset. I know this has already been answered but that fix does not solve my issue. 

__AttributeError: 'NeuroNER' object has no attribute 'sess'

**Comment by Franck-Dernoncourt** [comment] 2019-04-07 00:39
Thanks for the report, duplicate of #87 (see the [last comment](https://github.com/Franck-Dernoncourt/NeuroNER/issues/87#issuecomment-480507542) -> the issue is due to a recent update, will be fixed soon)

**Closed by Franck-Dernoncourt** 2019-04-07 00:39 UTC

**Comment by nishkalavallabhi** [comment] 2021-02-24 17:08
I just installed neuroner, and I have this exact same error (not with conll, but with a different dataset in bio, which works with other trainers). Is there a fix?

**Comment by garimazthakur** [comment] 2021-03-17 05:00
Please check your spacy module once.
