### ISSUE TITLE
error while running test_main.py

### ISSUE THREAD

**Issue by edvoinea** [Franck-Dernoncourt/NeuroNER#74] opened 2017-10-30 16:58 UTC
Executing: python3 test_main.py gives the following error log:

```
NeuroNER version: 1.0-dev
TensorFlow version: 1.3.0
{'character_embedding_dimension': 10,
 'character_lstm_hidden_state_dimension': 10,
 'check_for_digits_replaced_with_zeros': 1,
 'check_for_lowercase': 1,
 'dataset_text_folder': '../data/conll2003/en',
 'debug': 0,
 'dropout_rate': 0.5,
 'experiment_name': 'test',
 'freeze_token_embeddings': 0,
 'gradient_clipping_value': 5.0,
 'learning_rate': 0.005,
 'load_all_pretrained_token_embeddings': 0,
 'load_only_pretrained_token_embeddings': 0,
 'main_evaluation_mode': 'conll',
 'maximum_number_of_epochs': 2,
 'number_of_cpu_threads': 8,
 'number_of_gpus': 0,
 'optimizer': 'sgd',
 'output_folder': 'test/output',
 'parameters_filepath': 'test/test-parameters-training.ini',
 'patience': 10,
 'plot_format': 'pdf',
 'pretrained_model_folder': '../trained_models/conll_2003_en',
 'reload_character_embeddings': 1,
 'reload_character_lstm': 1,
 'reload_crf': 1,
 'reload_feedforward': 1,
 'reload_token_embeddings': 1,
 'reload_token_lstm': 1,
 'remap_unknown_tokens_to_unk': 1,
 'spacylanguage': 'en',
 'tagging_format': 'bioes',
 'token_embedding_dimension': 10,
 'token_lstm_hidden_state_dimension': 10,
 'token_pretrained_embedding_filepath': '',
 'tokenizer': 'spacy',
 'train_model': 1,
 'use_character_lstm': 1,
 'use_crf': 1,
 'use_pretrained_model': 0,
 'verbose': 0}
Checking the validity of BRAT-formatted train set... Done.
Checking compatibility between CONLL and BRAT for train_compatible_with_brat set ... Done.
/home/ed/NeuroNER-master/src/neuroner.py:153: ResourceWarning: unclosed file <_io.BufferedReader name='../data/conll2003/en/train_compatible_with_brat.txt'>
  conll_to_brat.check_compatibility_between_conll_and_brat_text(dataset_filepaths[dataset_type], dataset_brat_folders[dataset_type])
Checking validity of CONLL BIOES format... Done.
Checking the validity of BRAT-formatted valid set... Done.
Checking compatibility between CONLL and BRAT for valid_compatible_with_brat set ... Done.
/home/ed/NeuroNER-master/src/neuroner.py:153: ResourceWarning: unclosed file <_io.BufferedReader name='../data/conll2003/en/valid_compatible_with_brat.txt'>
  conll_to_brat.check_compatibility_between_conll_and_brat_text(dataset_filepaths[dataset_type], dataset_brat_folders[dataset_type])
Checking validity of CONLL BIOES format... Done.
Checking the validity of BRAT-formatted test set... Done.
Checking compatibility between CONLL and BRAT for test_compatible_with_brat set ... Done.
/home/ed/NeuroNER-master/src/neuroner.py:153: ResourceWarning: unclosed file <_io.BufferedReader name='../data/conll2003/en/test_compatible_with_brat.txt'>
  conll_to_brat.check_compatibility_between_conll_and_brat_text(dataset_filepaths[dataset_type], dataset_brat_folders[dataset_type])
Checking validity of CONLL BIOES format... Done.
Load dataset... done (24.40 seconds)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/ed/NeuroNER-master/src/neuroner.py:323: ResourceWarning: unclosed file <_io.BufferedWriter name='test/output/en_2017-10-30_18-48-39-77003/model/dataset.pickle'>
  pickle.dump(dataset, open(os.path.join(model_folder, 'dataset.pickle'), 'wb'))

Starting epoch 0
Training completed in 0.00 seconds
Evaluate model on the train set
processed 203621 tokens with 23499 phrases; found: 203621 phrases; correct: 3397.
accuracy:   2.44%; precision:   1.67%; recall:  14.46%; FB1:   2.99
              LOC: precision:   2.69%; recall:  22.66%; FB1:   4.81  60108
             MISC: precision:   1.41%; recall:  26.47%; FB1:   2.68  64389
              ORG: precision:   1.31%; recall:   7.44%; FB1:   2.22  35950
              PER: precision:   0.92%; recall:   6.05%; FB1:   1.60  43174

Evaluate model on the valid set
processed 51362 tokens with 5942 phrases; found: 51362 phrases; correct: 813.
accuracy:   2.27%; precision:   1.58%; recall:  13.68%; FB1:   2.84
              LOC: precision:   2.23%; recall:  18.89%; FB1:   3.99  15576
             MISC: precision:   1.38%; recall:  24.95%; FB1:   2.62  16661
              ORG: precision:   1.37%; recall:   8.95%; FB1:   2.38  8735
              PER: precision:   1.12%; recall:   6.30%; FB1:   1.90  10390

Evaluate model on the test set
processed 46435 tokens with 5648 phrases; found: 46435 phrases; correct: 745.
accuracy:   2.35%; precision:   1.60%; recall:  13.19%; FB1:   2.86
              LOC: precision:   2.38%; recall:  19.24%; FB1:   4.24  13478
             MISC: precision:   1.31%; recall:  26.50%; FB1:   2.50  14150
              ORG: precision:   1.32%; recall:   6.68%; FB1:   2.20  8413
              PER: precision:   1.22%; recall:   7.85%; FB1:   2.11  10394

Generating plots for the train set
/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E
======================================================================
ERROR: test_ProvideOutputDir_CorrectlyOutputsToDir (__main__.TestMain)
Sanity test to check if all proper model output files are created in the output folder
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_main.py", line 27, in test_ProvideOutputDir_CorrectlyOutputsToDir
    main.main(argv=['', '--output_folder', self.outputFolder,'--parameters_filepath', os.path.join(self.testFolder, 'test-parameters-training.ini')])
  File "/home/ed/NeuroNER-master/src/main.py", line 246, in main
    nn.fit()
  File "/home/ed/NeuroNER-master/src/neuroner.py", line 394, in fit
    evaluate.evaluate_model(results, dataset, y_pred, y_true, stats_graph_folder, epoch_number, epoch_start_time, output_filepaths, parameters)
  File "/home/ed/NeuroNER-master/src/evaluate.py", line 236, in evaluate_model
    verbose=verbose)
  File "/home/ed/NeuroNER-master/src/evaluate.py", line 19, in assess_model
    utils_plots.plot_classification_report(classification_report,title='Classification report for epoch {0} in {1} ({2} evaluation)\n'.format(epoch_number, dataset_type,evaluation_mode),cmap='RdBu')
  File "/home/ed/NeuroNER-master/src/utils_plots.py", line 162, in plot_classification_report
    heatmap(np.array(plotMat), title, xlabel, ylabel, xticklabels, yticklabels, figure_width, figure_height, correct_orientation, cmap=cmap)
  File "/home/ed/NeuroNER-master/src/utils_plots.py", line 112, in heatmap
    show_values(c, fmt=fmt)
  File "/home/ed/NeuroNER-master/src/utils_plots.py", line 36, in show_values
    ax = pc.get_axes()
AttributeError: 'PolyCollection' object has no attribute 'get_axes'

----------------------------------------------------------------------
Ran 1 test in 164.680s

FAILED (errors=1)
```

I am using matplotlib 2.1.0.

By doing the following change on line 36 in utils_plots.py seems to be working as expected at a glance.

```py
ax = pc.axes #changed from: ax = pc.get_axes()
```

**Comment by tompollard** [comment] 2019-01-24 19:23
Now fixed. Duplicate of https://github.com/Franck-Dernoncourt/NeuroNER/issues/76

**Closed by tompollard** 2019-01-24 19:23 UTC
