### ISSUE TITLE
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by essalahsouad** [Franck-Dernoncourt/NeuroNER#139] opened 2019-03-21 15:30 UTC
when i'm trying to test if the CUDA was successfully installed
`#Now let's see whether the GPU is here and CUDA was successfully installed!
import tensorflow as tf
device_name = tf.test.gpu_device_name()
print(device_name)
print("'sup!'")
i got this error

> ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

!/usr/local/cuda/bin/nvcc --version`
knowing that I already installed cuda8.0

`#Now, here's a bunch of code that takes the longest to execute here but
#It's about installing CUDA and using the beautiful Tesla K80 GPU, so that
#Will worth it
!apt update -qq;
!wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
!dpkg -i cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
!apt-get update -qq
#Here were are installing compilers and creating some links
!apt-get install cuda -y -qq #gcc-5 g++-5 
#!ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc
#!ln -s /usr/bin/g++-5 /usr/local/cuda/bin/g++
!apt update
!apt upgrade
!apt install cuda-8.0 -y`
**I use google colab**

**Comment by Franck-Dernoncourt** [comment] 2019-03-22 02:56
Duplicate of #66

**Closed by Franck-Dernoncourt** 2019-03-22 02:56 UTC
