### ISSUE TITLE
Add License to the codebase

### ISSUE THREAD

**Issue by chenzheruc** [Franck-Dernoncourt/NeuroNER#89] opened 2018-01-18 00:23 UTC
Hello, could you please add a license to the codebase? like Apache license?

**Comment by JohnGiorgi** [comment] 2018-01-18 00:25
Also mentioned in #46 and #15, no response yet from owner of the repository.

**Comment by tompollard** [comment] 2019-01-24 19:19
Duplicate of https://github.com/Franck-Dernoncourt/NeuroNER/issues/46, https://github.com/Franck-Dernoncourt/NeuroNER/issues/15

**Closed by tompollard** 2019-01-24 19:19 UTC
