### ISSUE TITLE
Does NeuroNER support nested NER models?

### ISSUE THREAD

**Issue by mosynaq** [Franck-Dernoncourt/NeuroNER#52] opened 2017-08-02 13:37 UTC
I am annotating a corpus to build modles with NeuroNER. Some entities appear to belong to two categories like the following:

[Sri Lanka]'s West coast: belongs to NORP in spaCy terminology
[Sri Lanka's West coast]: may belong to LOCATION, again in spaCy terminology
[<img src="https://image.ibb.co/mNMf75/Screenshot_from_2017_08_02_17_58_31.png">](image)
Can I use 'nested tagging' and set it as belonging to both categories? I mean can NeuroNER understand such tagging?

**Comment by Franck-Dernoncourt** [comment] 2017-08-02 13:41
NeuroNER unfortunately doesn't support it

**Comment by Gregory-Howard** [comment] 2017-08-04 15:12
Actually in the Conll format there is no double annotations (http://www.cnts.ua.ac.be/conll2003/ner/)
And the PERL script for calculating precision and recall uses CONLL format. (so even if NeuroNER can understand it it couldn't mesure a double category)
I would recommend using to NeuroNER models for Location and another one for Geo-political Entity. (I've done the test this changes nothing on the results).

Question Linked with #27

**Comment by Franck-Dernoncourt** [comment] 2017-08-05 03:27
+1 for what Gregory said, I'll close the question is duplicate of #27

**Closed** 2017-08-05 03:30 UTC
Labels: enhancement
