### ISSUE TITLE
Please add License version

### ISSUE THREAD

**Issue by purohitvivek8** [Franck-Dernoncourt/NeuroNER#111] opened 2018-06-07 09:05 UTC
Hello @Franck-Dernoncourt @toliwa @JohnGiorgi @jennyjylee @Gregory-Howard 
Please add license

**Comment by tompollard** [comment] 2019-01-24 19:19
Duplicate of https://github.com/Franck-Dernoncourt/NeuroNER/issues/89, https://github.com/Franck-Dernoncourt/NeuroNER/issues/46, https://github.com/Franck-Dernoncourt/NeuroNER/issues/15

**Closed by tompollard** 2019-01-24 19:19 UTC
