### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Mehty** [Franck-Dernoncourt/NeuroNER#103] opened 2018-03-29 18:10 UTC
I have followed the installation instructions for Mac OS, however when I run python3.5 main.py, I get the following error:

> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
NeuroNER version: 1.0-dev
TensorFlow version: 1.6.0
Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/Users/mehty/NeuroNER-master/src/neuroner.py", line 257, in __init__
    parameters, conf_parameters = self._load_parameters(arguments['parameters_filepath'], arguments=arguments)
  File "/Users/mehty/NeuroNER-master/src/neuroner.py", line 118, in _load_parameters
    parameters[k] = distutils.util.strtobool(v)
AttributeError: module 'distutils' has no attribute 'util'
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x104548a20>>
Traceback (most recent call last):
  File "/Users/mehty/NeuroNER-master/src/neuroner.py", line 489, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'

I tried removing and reinstalling all the required libraries but still got the same error. Would appreciate any help to resolve this issue.

**Comment by tricead** [comment] 2018-03-30 20:07
This is a duplicate of issues #87 and #75

**Comment by Mehty** [comment] 2018-03-30 20:21
Thank you.

**Closed** 2019-01-24 19:17 UTC
