### ISSUE TITLE
Plan to add a licence?

### ISSUE THREAD

**Issue by JohnGiorgi** [Franck-Dernoncourt/NeuroNER#46] opened 2017-07-26 15:14 UTC
First of all, I really appreciate all the work that went into NeuroNER, and how user-friendly you guys have been able to make it. 

Is there any plans to add a **licence** to the repo? I would love to fully commit to using NeuroNER for a non-commercial, academic project - but I do not want to pour more time and effort into the tool unless it will be (officially) open-source and free to use. 

I know this question has already been raised (#15), but as it was not answered I thought I would submit a new issue. 

Thanks again for creating this awesome tool!

**Comment by merryHunter** [comment] 2017-09-24 13:19
This issue is extremely important, as the tool may be used(or not) by companies for their NLP products. Please, pay attention to that!

**Comment by tompollard** [comment] 2019-01-24 19:19
Duplicate of https://github.com/Franck-Dernoncourt/NeuroNER/issues/15

**Closed by tompollard** 2019-01-24 19:19 UTC
